### ISSUE TITLE
Corrupt World

### ISSUE THREAD

**Issue by Nentify** [TinyModularThings/IC2Classic#110]
```
[17:09:02] [Server thread/FATAL] [FML]: The world state is utterly corrupted and this save is NOT loadable

There is a high probability that a mod has broken the
ID map and there is
NOTHING FML or Forge can do to recover this save.

If you changed your mods, try reverting the change
java.lang.IllegalStateException: Can't map block minecraft:bookshelf to id -1 (seen at: 0), already occupied by null, blocked false, ItemBlock false
	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:525) ~[GameData.class:?]
	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) [FMLContainer.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:220) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

After turning off some recipes (eg nuke, iTNT, coins), I restarted my game and got the corruption message. Is this normal? Should I just use MineTweaker to change recipes in future?

**Comment by Speiger** [comment]
O.o whats that o.O

**Comment by Nentify** [comment]
Hmm, I can't reproduce it on a new world... I think it might be related to this though. Turning off oregen turns off ore blocks completely:

![](http://i.nentify.me/V9BMqR16.png)

**Comment by Nentify** [comment]
Uh sorry. Are the ores meant to be disabled completely like that? If so, you can probably just close this issue.

**Comment by Speiger** [comment]
yeah it is. Ores will be removed with the orgen so that they do not exsist anymore... (MFR laserdrill)

**Comment by Carbon-Ghost** [comment]
WTF, Speiger, are you drunk ? You want to remove ores with oregen ? Stop :beers:

**Comment by Speiger** [comment]
@Carbon-Ghost thats IC2 original code! Was in every IC2 version i think it was still in the 1.6.4 version of IC2 Exp...

**Comment by Carbon-Ghost** [comment]
Wait, I don't understand, do you mean the config for allowing oregen or you want to completely remove oregen from IC2 O.o ?

**Comment by Speiger** [comment]
The config for orgen dissables not only the orgen it also prevents that the Oreblock get loaded at all. OreGen = false = You can not find any IC2 Copper Ore (example)

**Comment by Carbon-Ghost** [comment]
Oh kk, but just how you wrote it sounded like you wanted to remove completely IC2 oregen xD Hence the :beer:

**Comment by Speiger** [comment]
@Carbon-Ghost -.- Wow i know that i explain stupid but are you that blind?

**Comment by Carbon-Ghost** [comment]
Well with -3,75 both eyes, I do have an excuse for that :P lol ( gonna admit that's kinda fucking annoying when doing parkour or anything were perception is something that kinda will save your life ) but TL;DR yup.

**Comment by Speiger** [comment]
Well i have -4,75 also for both eyes... Really short range. I could not even watch videos on my pc when i would not have my glasses... (Coding is also then not possible)

**Comment by Carbon-Ghost** [comment]
Lol, I can TRY to do something on my computer but then I zoom 3x more at the very least, but then I get SUPER HEADACHE OF DEATH D: 

Also, off topic but I can't find NG NL Vostfr D: ( subtitled in french ) ;_;

**Comment by Speiger** [comment]
xD Well @Carbon-Ghost xD i know that.
I have no French-Sub NGNL... But i have a Eng-Sub NGNL if you want it.

**Comment by Carbon-Ghost** [comment]
I WANT IT ( if it's subtitles :D :D :D )

**Comment by Speiger** [comment]
Closing because no longer a bug
