### ISSUE TITLE
[1.19.2] After leaving the server, the console says:

### ISSUE THREAD

**Issue by Raportuy** [TinyModularThings/IC2Classic#1146]
To reproduce:
- Login to the server
- Disconnect from the server

LOG:
[08:05:08] [Server thread/INFO] [minecraft/MinecraftServer]: Raportuy joined the game
[08:05:08] [Server thread/INFO] [Jade/]: Syncing config to Raportuy (4afe2ede-f6e5-3c58-bf7e-45eb2fbdf6df)
[08:05:10] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2060ms or 41 ticks behind
[08:24:37] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Raportuy lost connection: Disconnected
[08:24:37] [Server thread/INFO] [minecraft/MinecraftServer]: Raportuy left the game
[08:29:46] [Finalizer/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        Index: 3
        Listeners:
                0: HIGHEST
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@3dba2475 onDimensionUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                2: NORMAL
                3: ASM: ic2.core.platform.events.IC2EventHandler@65c08f9e onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                4: ASM: ic2.core.platform.events.StructureManager@67e83e3f onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                5: ASM: ic2.core.platform.events.MultiBlockManager@1d1c310 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
java.lang.NullPointerException: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.IC2EventHandler.onWorldUnload(IC2EventHandler.java:479)
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.__IC2EventHandler_onWorldUnload_Unload.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/smallerunits@2.1.3/tfc.smallerunits.simulation.level.server.TickerServerLevel.finalize(TickerServerLevel.java:141)
        at java.base/java.lang.System$2.invokeFinalize(System.java:2301)
        at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
        at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
        
Mods:
IC2Classic-1.19.2-2.0.9.1.jar
advancedsolars-2.0.5.jar
gravisuit-2.3.jar

**Comment by Speiger** [comment]
@Raportuy you must run somehting that runs the event client sided on a MP server because that isn't looking right.
Or you must run a server that is not supporting the features required

**Comment by Raportuy** [comment]
> @Raportuy you must run somehting that runs the event client sided on a MP server because that isn't looking right. Or you must run a server that is not supporting the features required
Sorry, I'm a Russian-speaking person, and the translator somehow translates your words incorrectly, I don't understand what does it mean to trigger an event? What event? Where?
And why do you say that I need a server that does not support the necessary functions? What functions? What server?
I play on the server with the mods listed above. How do I remove it? 
Today it's been like that again:
[16:06:13] [Finalizer/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        Index: 3
        Listeners:
                0: HIGHEST
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@35424a44 onDimensionUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                2: NORMAL
                3: ASM: ic2.core.platform.events.IC2EventHandler@30968b90 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                4: ASM: ic2.core.platform.events.StructureManager@41eceff2 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                5: ASM: ic2.core.platform.events.MultiBlockManager@65efa50e onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                6: LOWEST
                7: ASM: org.dynmap.forge_1_19_2.DynmapPlugin$WorldTracker@2fa71769 handleWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
java.lang.NullPointerException: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.IC2EventHandler.onWorldUnload(IC2EventHandler.java:479)
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.__IC2EventHandler_onWorldUnload_Unload.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/smallerunits@2.1.3/tfc.smallerunits.simulation.level.server.TickerServerLevel.finalize(TickerServerLevel.java:141)
        at java.base/java.lang.System$2.invokeFinalize(System.java:2301)
        at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
        at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
[16:06:13] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 3075ms or 61 ticks behind
[16:06:13] [Finalizer/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        Index: 3
        Listeners:
                0: HIGHEST
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@35424a44 onDimensionUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                2: NORMAL
                3: ASM: ic2.core.platform.events.IC2EventHandler@30968b90 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                4: ASM: ic2.core.platform.events.StructureManager@41eceff2 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                5: ASM: ic2.core.platform.events.MultiBlockManager@65efa50e onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                6: LOWEST
                7: ASM: org.dynmap.forge_1_19_2.DynmapPlugin$WorldTracker@2fa71769 handleWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
java.lang.NullPointerException: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.IC2EventHandler.onWorldUnload(IC2EventHandler.java:479)
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.__IC2EventHandler_onWorldUnload_Unload.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/smallerunits@2.1.3/tfc.smallerunits.simulation.level.server.TickerServerLevel.finalize(TickerServerLevel.java:141)
        at java.base/java.lang.System$2.invokeFinalize(System.java:2301)
        at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
        at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
[16:06:13] [Finalizer/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        Index: 3
        Listeners:
                0: HIGHEST
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@35424a44 onDimensionUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                2: NORMAL
                3: ASM: ic2.core.platform.events.IC2EventHandler@30968b90 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                4: ASM: ic2.core.platform.events.StructureManager@41eceff2 onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                5: ASM: ic2.core.platform.events.MultiBlockManager@65efa50e onWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
                6: LOWEST
                7: ASM: org.dynmap.forge_1_19_2.DynmapPlugin$WorldTracker@2fa71769 handleWorldUnload(Lnet/minecraftforge/event/level/LevelEvent$Unload;)V
java.lang.NullPointerException: Cannot invoke "ic2.core.networking.NetworkManager.onWorldUnload(net.minecraft.world.level.Level)" because the return value of "ic2.core.utils.SidedGateway.get()" is null
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.IC2EventHandler.onWorldUnload(IC2EventHandler.java:479)
        at TRANSFORMER/ic2@1.19.2-2.0.9.1/ic2.core.platform.events.__IC2EventHandler_onWorldUnload_Unload.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/smallerunits@2.1.3/tfc.smallerunits.simulation.level.server.TickerServerLevel.finalize(TickerServerLevel.java:141)
        at java.base/java.lang.System$2.invokeFinalize(System.java:2301)
        at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
        at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)

**Comment by Speiger** [comment]
sorry but i don't know
