### ISSUE TITLE
1.12.2 randon server crash

### ISSUE THREAD

**Issue by Nbgreen** [TinyModularThings/IC2Classic#1165]
[00:46:54] [Server thread/ERROR] [FML]: Exception caught during firing event ic2.api.energy.event.EnergyTileUnloadEvent@7e070ea5:
java.lang.NullPointerException: null
	at ic2.core.energy.EnergyNetLocal.removeFromGrids(EnergyNetLocal.java:1470) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:1460) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.removeTile(EnergyNetLocal.java:1387) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetGlobal$EventHandler.onEnergyTileUnload(EnergyNetGlobal.java:395) ~[EnergyNetGlobal$EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.9-140.jar:1.12.2-5.9-140]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) [EventBus.class:?]
	at mekanism.common.tile.prefab.TileEntityElectricBlock.deregister(TileEntityElectricBlock.java:73) [TileEntityElectricBlock.class:?]
	at mekanism.common.tile.prefab.TileEntityElectricBlock.onChunkUnload(TileEntityElectricBlock.java:142) [TileEntityElectricBlock.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1808) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3931) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
[00:46:54] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[00:46:54] [Server thread/ERROR] [FML]: 0: NORMAL
[00:46:54] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.energy.EnergyNetGlobal$EventHandler@5d3a784c onEnergyTileUnload(Lic2/api/energy/event/EnergyTileUnloadEvent;)V
[00:46:54] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent)
[00:46:54] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world entities
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
Caused by: java.lang.NullPointerException
	at ic2.core.energy.EnergyNetLocal.removeFromGrids(EnergyNetLocal.java:1470) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:1460) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.removeTile(EnergyNetLocal.java:1387) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetGlobal$EventHandler.onEnergyTileUnload(EnergyNetGlobal.java:395) ~[EnergyNetGlobal$EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.9-140.jar:1.12.2-5.9-140]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) ~[EventBus.class:?]
	at mekanism.common.tile.prefab.TileEntityElectricBlock.deregister(TileEntityElectricBlock.java:73) ~[TileEntityElectricBlock.class:?]
	at mekanism.common.tile.prefab.TileEntityElectricBlock.onChunkUnload(TileEntityElectricBlock.java:142) ~[TileEntityElectricBlock.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1808) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3931) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

**Comment by Nbgreen** [comment]
java.lang.NullPointerException
    at ic2.core.energy.EnergyNetLocal.removeFromGrids(EnergyNetLocal.java:1470)
    at ic2.core.energy.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:1460)
    at ic2.core.energy.EnergyNetLocal.removeTile(EnergyNetLocal.java:1387)
    at ic2.core.energy.EnergyNetGlobal$EventHandler.onEnergyTileUnload(EnergyNetGlobal.java:395)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_422_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)
    at mekanism.common.tile.prefab.TileEntityElectricBlock.deregister(TileEntityElectricBlock.java:73)
    at mekanism.common.tile.prefab.TileEntityElectricBlock.onChunkUnload(TileEntityElectricBlock.java:142)
    at net.minecraft.world.World.updateEntities(World.java:1808)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3931)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
