### ISSUE TITLE
Sound unloading crash

### ISSUE THREAD

**Issue by Bluedog444** [TinyModularThings/IC2Classic#117]
Hi, I was flying away from by base when I crashed.
I think its the Ic2 sound unloading after I left the sound radius from my geothermal generators.

Time: 9/25/15 7:07 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at paulscode.sound.SoundSystem.removeSource(SoundSystem.java:1258)
	at ic2.core.audio.AudioSourceClient.remove(AudioSourceClient.java:73)
	at ic2.core.audio.AudioManagerClient.removeSources(AudioManagerClient.java:261)
	at ic2.core.block.generator.tileentity.TileEntityBaseGenerator.onUnloaded(TileEntityBaseGenerator.java:97)
	at ic2.core.block.TileEntityBlock.onChunkUnload(TileEntityBlock.java:72)
	at net.minecraft.world.World.func_72939_s(World.java:1979)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Speiger** [comment]
@Bluedog444 again here... Please tell me if that happens with 1.2.0.0

**Comment by Bluedog444** [comment]
@Speiger Oh these were very old versions of the mod. I doubt it happens now.
