### ISSUE TITLE
[1.7.10] Something really bad happened on Integration at load stage POST_INIT 

### ISSUE THREAD

**Issue by huntindeed** [TinyModularThings/IC2Classic#1213]
Doesn't happen with basic Industrial Craft

[20:59:05] [Client thread/INFO] [IC2]: Loaded minor compatibility modules: none
[20:59:05] [Client thread/ERROR] [UniDict]: Something really bad happened on Integration at load stage POST_INIT

Caused by: java.lang.NoSuchFieldError: input
at wanion.unidict.recipe.IC2RecipeResearcher.getShapelessRecipeKey(IC2RecipeResearcher.java:63)
at wanion.unidict.integration.CraftingIntegration.doTheResearch(CraftingIntegration.java:75)
at wanion.unidict.integration.CraftingIntegration.call(CraftingIntegration.java:58)
at wanion.unidict.integration.CraftingIntegration.call(CraftingIntegration.java:33)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by Speiger** [comment]
@segoitch not ic2c crashing but Unidict. 
Next time don't dump the crashlog in there but provide a link to such a thing.

**Comment by huntindeed** [comment]
> @segoitch not ic2c crashing but Unidict. Next time don't dump the crashlog in there but provide a link to such a thing.

If I send a link next time, will you fix it and not just close the issue?

**Comment by Meduris** [comment]
> > @segoitch not ic2c crashing but Unidict. Next time don't dump the crashlog in there but provide a link to such a thing.
> 
> If I send a link next time, will you fix it and not just close the issue?

as Speiger said in his message (first line) this is caused by Unidict. It is not our issue to fix but rather theirs
