### ISSUE TITLE
Luminators erroring

### ISSUE THREAD

**Issue by bigstiffy** [TinyModularThings/IC2Classic#159]
I've been testing stuff server side, and it seems that luminator tile entities occasionally error, and breaking or removing them by any means causes infinite luminators to spawn from the location of the tile entity, until you place a luminator back in it's place. It seems to only affect a chunk, when it happens, rather than everything on the power net.
Only way I found to remove them was forcing a crash by placing ultra-low-current cable in the space the luminator used to occupy.

`Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at ic2.core.block.wiring.TileEntityLuminator.func_145845_h(TileEntityLuminator.java:161)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Head --
Stacktrace:
	at ic2.core.block.wiring.TileEntityLuminator.func_145845_h(TileEntityLuminator.java:161)

-- Block entity being ticked --
Details:
	Name: Luminator // ic2.core.block.wiring.TileEntityLuminator
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (705,53,834), Chunk: (at 1,3,2 in 44,52; contains blocks 704,0,832 to 719,255,847), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)`

**Comment by Speiger** [comment]
yeah luminators are done horribly... I will change them so that they work better... But the next update is at least 1 month away so keep that in mind...

**Comment by bigstiffy** [comment]
No worries, just didn't any an existing bug report.

**Comment by Speiger** [comment]
i think i will also add multipart kinda like cables that supports lights on the same block...
they will not support FMP

**Comment by modmuss50** [comment]
If you want fmp cables I've done it

**Comment by Speiger** [comment]
@modmuss50 its about making Plugs for wires that you can then have lamps on so that you do not need to have a seperate block... And no FMP support as long it is so buggy....

**Comment by modmuss50** [comment]
ah, no I cannot do that, was thinking of something else. And FMP does have its issues.

**Comment by bigstiffy** [comment]
I fully endorse the idea of luminators occupying cable space, or socket cables.

**Comment by Speiger** [comment]
Fixed & Improved
