### ISSUE TITLE
Crash watermill (Beta Build)

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#166]
Hello my friend. When installing the water mill in the world is going on crash the server and client.

Unexpected error

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at ic2.core.block.generator.tileentity.TileEntityWaterGenerator.updateWaterCount(TileEntityWaterGenerator.java:167)
	at ic2.core.block.generator.tileentity.TileEntityWaterGenerator.onLoaded(TileEntityWaterGenerator.java:54)
	at ic2.core.block.TileEntityBlock.func_145829_t(TileEntityBlock.java:51)
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:886)
	at net.minecraft.world.World.func_147455_a(World.java:2600)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 31 more
Caused by: java.lang.NullPointerException

**Comment by Speiger** [comment]
xDD Thanks i will take care of that..
Just a question is that a test build?
Also Check your IC2 Forum PMs i sended you something.

**Comment by Dr0n1k** [comment]
Yes, its last version from dropbox.

**Comment by Speiger** [comment]
ok.

**Comment by Speiger** [comment]
fixed
