### ISSUE TITLE
Fluid-O-Mat

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#21]
Just doing as Forge says:

[23:25:35] [Server thread/ERROR] [FML]: A TileEntity type ic2.core.block.personal.TileEntityFluidOMat has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class ic2.core.block.personal.TileEntityFluidOMat is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at ic2.core.block.TileEntityBlock.func_145841_b(TileEntityBlock.java:101) ~[TileEntityBlock.class:?]
	at ic2.core.block.machine.tileentity.TileEntityMachine.func_145841_b(TileEntityMachine.java:104) ~[TileEntityMachine.class:?]
	at ic2.core.block.personal.TileEntityFluidOMat.func_145841_b(TileEntityFluidOMat.java:61) ~[TileEntityFluidOMat.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:181) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by Speiger** [comment]
Forgot the mapping in 1.7.10

**Comment by Speiger** [comment]
Fixed.
