### ISSUE TITLE
1.7.10 - NPE when the fluid or energy o'mat contains any similar items

### ISSUE THREAD

**Issue by Ghostlyr** [TinyModularThings/IC2Classic#243]
```
java.lang.NullPointerException: Ticking block entity
	at ic2.core.block.personal.TileEntityFluidOMat.func_145845_h(TileEntityFluidOMat.java:246)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
```
java.lang.NullPointerException: Ticking block entity
	at ic2.core.block.personal.TileEntityEnergyOMat.func_145845_h(TileEntityEnergyOMat.java:187)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Steps to reproduce:

![2017-12-03_18 12 52](https://user-images.githubusercontent.com/8511068/33525283-a6270baa-d856-11e7-95ae-fd8013da0a6d.png)
![2017-12-03_18 14 43](https://user-images.githubusercontent.com/8511068/33525282-a5fc395c-d856-11e7-824e-16d1df4df9b8.png)

MC 1.7.10 / Forge 1614
IC: 1.2.1.5.2

**Comment by Speiger** [comment]
Oh my OK I check that out.
