### ISSUE TITLE
Bad items labels

### ISSUE THREAD

**Issue by PavloosCzM** [TinyModularThings/IC2Classic#377]
[11:44:43] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[11:44:43] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_231, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_231

[11:45:09] [Server thread/ERROR] [FML]: Parsing error loading recipe energyconverters:energy_producer_eu_3
com.google.gson.JsonSyntaxException: Unknown item 'ic2:cable'
	at net.xalcon.energyconverters.common.crafting.IngredientFactoryVanillaNBT.parse(IngredientFactoryVanillaNBT.java:32) ~[IngredientFactoryVanillaNBT.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:204) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.oredict.ShapedOreRecipe.factory(ShapedOreRecipe.java:216) ~[ShapedOreRecipe.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339) [FMLCommonHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:45:09] [Server thread/ERROR] [FML]: Parsing error loading recipe energyconverters:energy_producer_eu_0
com.google.gson.JsonSyntaxException: Unknown item 'ic2:cable'
	at net.xalcon.energyconverters.common.crafting.IngredientFactoryVanillaNBT.parse(IngredientFactoryVanillaNBT.java:32) ~[IngredientFactoryVanillaNBT.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:204) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.oredict.ShapedOreRecipe.factory(ShapedOreRecipe.java:216) ~[ShapedOreRecipe.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339) [FMLCommonHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:45:09] [Server thread/ERROR] [FML]: Parsing error loading recipe energyconverters:energy_producer_eu_2
com.google.gson.JsonSyntaxException: Unknown item 'ic2:cable'
	at net.xalcon.energyconverters.common.crafting.IngredientFactoryVanillaNBT.parse(IngredientFactoryVanillaNBT.java:32) ~[IngredientFactoryVanillaNBT.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:204) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.oredict.ShapedOreRecipe.factory(ShapedOreRecipe.java:216) ~[ShapedOreRecipe.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339) [FMLCommonHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:45:09] [Server thread/ERROR] [FML]: Parsing error loading recipe energyconverters:energy_producer_eu_4
com.google.gson.JsonSyntaxException: Unknown item 'ic2:cable'
	at net.xalcon.energyconverters.common.crafting.IngredientFactoryVanillaNBT.parse(IngredientFactoryVanillaNBT.java:32) ~[IngredientFactoryVanillaNBT.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:204) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.oredict.ShapedOreRecipe.factory(ShapedOreRecipe.java:216) ~[ShapedOreRecipe.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339) [FMLCommonHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:45:09] [Server thread/ERROR] [FML]: Parsing error loading recipe energyconverters:energy_producer_eu_1
com.google.gson.JsonSyntaxException: Unknown item 'ic2:cable'
	at net.xalcon.energyconverters.common.crafting.IngredientFactoryVanillaNBT.parse(IngredientFactoryVanillaNBT.java:32) ~[IngredientFactoryVanillaNBT.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:204) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.oredict.ShapedOreRecipe.factory(ShapedOreRecipe.java:216) ~[ShapedOreRecipe.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339) [FMLCommonHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:45:09] [Server thread/ERROR] [FML]: Parsing error loading recipe powersuits:ic2_classic/components/component_lv_capacitor
com.google.gson.JsonParseException: Missing data for item 'ic2:itemBatRE'
	at net.machinemuse.numina.recipe.NuminaShapedRecipe.deserializeItem(NuminaShapedRecipe.java:184) ~[NuminaShapedRecipe.class:?]
	at net.machinemuse.numina.recipe.NuminaShapedRecipe.deserializeIngredient(NuminaShapedRecipe.java:153) ~[NuminaShapedRecipe.class:?]
	at net.machinemuse.numina.recipe.NuminaShapedRecipe.deserializeKey(NuminaShapedRecipe.java:141) ~[NuminaShapedRecipe.class:?]
	at net.machinemuse.numina.recipe.NuminaShapedRecipe.deserialize(NuminaShapedRecipe.java:39) ~[NuminaShapedRecipe.class:?]
	at net.machinemuse.powersuits.recipe.MPSRecipeFactory.parse(MPSRecipeFactory.java:12) ~[MPSRecipeFactory.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339) [FMLCommonHandler.class:git-CatServer-1.12.2-4805974]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by Speiger** [comment]
What is exactly the issue? IC2API names are for modcompat not the registry names

**Comment by PavloosCzM** [comment]
Server writes me these errors, I thought you might have badly named items in your code?

**Comment by Speiger** [comment]
@PavloosCzM this looks more like you installed a mod that expects IC2Experimental to be installed?

**Comment by Trinsdar** [comment]
Yah it's because the json recipes are looking for ic2 experimental item ids
