### ISSUE TITLE
IC2 Classic does not stop it's sounds when disconnecting from a server in unusual way

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#410]
## Steps to reproduce:
1. Start a dedicated server
2. Put a machine which make noise (e.g. geothermal generator)
3. /stop
4. Minecraft client continue to play loop sound

And if you reload sound system (manually (using dynamic surroundings) or if it crash somehow), trying to do anything that plays sound will crash the client:
```
java.lang.NullPointerException
    at paulscode.sound.SoundSystem.quickPlay(SoundSystem.java:857)
    at ic2.core.audio.AudioManagerClient.playOnce(AudioManagerClient.java:208)
    at ic2.core.item.tool.ItemToolWrench.onItemUseFirst(ItemToolWrench.java:136)
    at ic2.core.item.tool.electric.ItemElectricToolWrench.onItemUseFirst(ItemElectricToolWrench.java:125)
    at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:409)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1579)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
```

**Comment by Speiger** [comment]
Thats why in the Audiosettings there is a category for IC2C and to delete all active sounds.

**Comment by Speiger** [comment]
Also this could be something related to dynamic soroundings.
Can you reproduce that without any audio changing addons?

**Comment by DBotThePony** [comment]
If you are about crash - you can also reproduce this bug by reloading sound interfaces in Linux. But easiest way to reproduce the crash on your side - is to install dynamic surroundings and using it's sound system restart hotkey

**Comment by Speiger** [comment]
I wasn't mainly talking about the crash but the audio itself during the main menu.

It might be that the linux version does something different. Though the audio bugs (not the crash) have to be reproduced without dynamic surroundings, they might change the audio engine.

**Comment by DBotThePony** [comment]
Sound bug still appear in main menu but for a very short period with only ic2c installed. Installing Dynamic Surroundings brings back the problem.
**However.**
IC2C is the only one mod i've seen in years which has problems with Dynamic Surroundings' sound replacement (and never saw any mod with looped sounds to break, even with DS' manual sound system reload).

**Comment by Speiger** [comment]
Yeah IC2C has a custom audio manager that uses MCs audio engine to achieve better sound effects.
Stuff like: Traced Loudness (taking the world into account) is a feature that it does.
And the audioengine also deletes all sounds. It might take a second but I installed a cleanup function.
That this function does not work is a bug of Dynamic Surroundings.
I can provide them data for how we do it but this feature exists exactly the same way for over multiple Minecraft versions (at least 1.2.5)

**Comment by Speiger** [comment]
TL:DR
You stated it yourself. It "ONLY" happens with dynamic Dynamic Surroundings.
That means Dynamic Surroundings changes something that should not be changed.

So closing issue.
