### ISSUE TITLE
Crash server when churning crops

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#44]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at ic2.core.block.crop.IC2Crops.getHumidityBiomeBonus(IC2Crops.java:110)
	at ic2.core.block.TileEntityCrop.updateHumidity(TileEntityCrop.java:870)
	at ic2.core.block.TileEntityCrop.getHumidity(TileEntityCrop.java:843)
	at ic2.core.block.TileEntityCrop.calcGrowthRate(TileEntityCrop.java:962)
	at ic2.core.block.TileEntityCrop.tick(TileEntityCrop.java:184)
	at ic2.core.block.TileEntityCrop.func_145845_h(TileEntityCrop.java:117)
	at net.minecraft.world.World.func_72939_s(World.java:2511)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.block.crop.IC2Crops.getHumidityBiomeBonus(IC2Crops.java:110)
	at ic2.core.block.TileEntityCrop.updateHumidity(TileEntityCrop.java:870)
	at ic2.core.block.TileEntityCrop.getHumidity(TileEntityCrop.java:843)
	at ic2.core.block.TileEntityCrop.calcGrowthRate(TileEntityCrop.java:962)
	at ic2.core.block.TileEntityCrop.tick(TileEntityCrop.java:184)
	at ic2.core.block.TileEntityCrop.func_145845_h(TileEntityCrop.java:117)

Server Version: Cauldron Forge 1.7.10
Forge Version: 10.13.3.1403

**Comment by Speiger** [comment]
Thanks. I will fix that with the next update.

**Comment by Speiger** [comment]
Fixed. Also removed a potential crash too.
