### ISSUE TITLE
Issue crafting items from IC2C (and piston)

### ISSUE THREAD

**Issue by Alyssalove27** [TinyModularThings/IC2Classic#451]
Hello! I have an issue regarding my personal modpack in a server environment... Works fine in singleplayer though!

Whenever I try to craft something from IC2C in a crafting table, recipe has no output (recipe is registered in JEI)... the server log outputs an error but no crash or disconnect... nothing happens.

I tried with a generator, a geothermal generator, and a piston.

I have GT classic and GTC expansion... May be related to that too.

Partial log, the error that comes up whenever the recipe is complete (but not taken out of the crafting table, there's nothing in the output slot!).

```
[20:21:47] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: ic2/core/util/StackUtil
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: ic2/core/util/StackUtil
	at aroma1997.tatw.feuseseu.item.EnergyItemImpl.handles(EnergyItemImpl.java:105) ~[EnergyItemImpl.class:?]
	at ic2.api.item.ElectricItem.getBackupManager(ElectricItem.java:50) ~[ElectricItem.class:?]
	at ic2.core.item.manager.GatewayElectricItemManager.getManager(GatewayElectricItemManager.java:143) ~[GatewayElectricItemManager.class:?]
	at ic2.core.item.manager.GatewayElectricItemManager.getCharge(GatewayElectricItemManager.java:45) ~[GatewayElectricItemManager.class:?]
	at ic2.core.item.recipe.AdvRecipe.func_77572_b(AdvRecipe.java:365) ~[AdvRecipe.class:?]
	at net.minecraft.inventory.Container.func_192389_a(Container.java:798) ~[afr.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:51) ~[afz.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: ic2.core.util.StackUtil
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at aroma1997.tatw.feuseseu.item.EnergyItemImpl.handles(EnergyItemImpl.java:105) ~[EnergyItemImpl.class:?]
	at ic2.api.item.ElectricItem.getBackupManager(ElectricItem.java:50) ~[ElectricItem.class:?]
	at ic2.core.item.manager.GatewayElectricItemManager.getManager(GatewayElectricItemManager.java:143) ~[GatewayElectricItemManager.class:?]
	at ic2.core.item.manager.GatewayElectricItemManager.getCharge(GatewayElectricItemManager.java:45) ~[GatewayElectricItemManager.class:?]
	at ic2.core.item.recipe.AdvRecipe.func_77572_b(AdvRecipe.java:365) ~[AdvRecipe.class:?]
	at net.minecraft.inventory.Container.func_192389_a(Container.java:798) ~[afr.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:51) ~[afz.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
```

Full log here:
[latest.log](https://github.com/TinyModularThings/IC2Classic/files/5884215/latest.log)

**Comment by Speiger** [comment]
at aroma1997.tatw.feuseseu.item.EnergyItemImpl.handles(EnergyItemImpl.java:105) ~[EnergyItemImpl.class:?]

tatw is not compatible with IC2Classic. Not a bug.

**Comment by Alyssalove27** [comment]
Oh my... didn't think TATW would cause a recipe issue! :o Removed!

Works wonders now!

Thankies!
