### ISSUE TITLE
Crash client/server Fluid-O-Mat

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#49]
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at ic2.core.block.personal.ContainerFluidOMatOpen.func_75137_b(ContainerFluidOMatOpen.java:114)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at ic2.core.block.personal.ContainerFluidOMatOpen.func_75137_b(ContainerFluidOMatOpen.java:114)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

Server Version: Cauldron Forge 1.7.10
 Forge Version: 10.13.3.1403

**Comment by Chocohead** [comment]
Likely being affected from new fluid system in Forge

**Comment by Speiger** [comment]
Downgrade your forge so low as you can (optimal would be down to the Recomented version) because IC2 uses only stabel forge builds.

**Comment by Dr0n1k** [comment]
Thanks for the answer. But unfortunately I can not downgrade Forge. I'll look forward to when the new Forge will be stable, and you can update the Fluid-O-Mat to a new kind of fluids.

**Comment by Speiger** [comment]
No Problem. It is cool that someone uses the fluid o mat xD

**Comment by Speiger** [comment]
At the moment Closed because there is nothing i can do and it should be not spamming the important sutff...
