### ISSUE TITLE
Crash client/server Cropmatron

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#50]
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77972_a(ItemStack.java:270)
	at ic2.core.block.machine.tileentity.TileEntityCropmatron.scan(TileEntityCropmatron.java:123)
	at ic2.core.block.machine.tileentity.TileEntityCropmatron.func_145845_h(TileEntityCropmatron.java:80)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77972_a(ItemStack.java:270)
	at ic2.core.block.machine.tileentity.TileEntityCropmatron.scan(TileEntityCropmatron.java:123)
	at ic2.core.block.machine.tileentity.TileEntityCropmatron.func_145845_h(TileEntityCropmatron.java:80)

Server Version: Cauldron Forge 1.7.10
Forge Version: 10.13.3.1403

**Comment by Speiger** [comment]
@Dr0n1k thanks for that bugreport. To prevent that do not use WeedEx in the Cropmatron. That is causing it...

**Comment by Speiger** [comment]
Fixed. Thanks for that report.
