### ISSUE TITLE
Crash server Trade-O-Mat

### ISSUE THREAD

**Issue by MrcreativeBC** [TinyModularThings/IC2Classic#55]
Time: 6/2/15 12:49 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at ic2.core.block.personal.TileEntityTradeOMat.updateStock(TileEntityTradeOMat.java:170)
	at ic2.core.block.personal.TileEntityTradeOMat.onLoaded(TileEntityTradeOMat.java:153)
	at ic2.core.block.TileEntityBlock$1.tickCallback(TileEntityBlock.java:60)
	at ic2.core.IC2.onTickStart(IC2.java:1892)
	at ic2.core.IC2.onWorldTick(IC2.java:1809)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_IC2_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:914)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Speiger** [comment]
@MrcreativeBC ok, a little bit more information would be good.
How did that happen?
What blocks were next to the TradeOMat and also when did it happen?
That would make my life way easier.

**Comment by MrcreativeBC** [comment]
I just connected the vending machine to the trunk, and then there was a crash.

**Comment by Speiger** [comment]
ok From which mod is the trunk?

**Comment by Speiger** [comment]
Should be fixed but it need to be tested... I can not do that alone that easy. I hope that it will not crash anymore...
