### ISSUE TITLE
NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)"

### ISSUE THREAD

**Issue by innerdev** [TinyModularThings/IC2Classic#595]
Hello.

I just start playing the mod. It is installed on my dedicated server. Today I started to get the following error with server crash after it:

```[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: ic2.core.platform.events.IC2EventHandler@96a2cf1 onWorldTickEvent(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                2: ASM: me.lucko.spark.forge.ForgeTickHook@c52710a onTick(Lnet/minecraftforge/event/TickEvent;)V
                3: ASM: me.lucko.spark.forge.ForgeTickReporter@664fb61d onTick(Lnet/minecraftforge/event/TickEvent;)V
                4: ASM: class ru.innerdev.pelog.Pelog onEvent(Lnet/minecraftforge/eventbus/api/Event;)V
java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:866)
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:242)
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206)
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:136)
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161)
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:441)
        at TRANSFORMER/ic2@1.19.2-2.0.2/ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@43.2.3/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)

[25янв.2023 00:52:27.451] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
        at ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:866) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:242) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:136) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:441) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic) ~[IC2Classic-1.19.2-2.0.2.jar%23110!/:1.19.2-2.0.2]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-43.2.3-universal.jar%23122!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23117!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23117!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23117!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23117!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23117!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID f0df41ee-ba53-4c6b-b629-b390c1e02bfc
[Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /var/games/mc1/./crash-reports/crash-2023-01-25_00.52.27-server.txt
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
```

Can you help me, please? Version: 2.0.2 or 2.0.3 (result is the same). Minecraft version: 1.19.2, Forge version 43.2.3

**Comment by innerdev** [comment]
As I can see it's duplicate of https://github.com/TinyModularThings/IC2Classic/issues/529
Well, I have world backup, logs, everything (I hope) you need to debug this problem.
Can you PM me in Discord? It's me: innerdev#6184

**Comment by innerdev** [comment]
@Speiger (cast you just in case)

**Comment by Speiger** [comment]
@innerdev is it a easy to reproduce able setup?
Also on the curseforge page you can find the ic2c discord server.

**Comment by innerdev** [comment]
> @innerdev is it a easy to reproduce able setup? Also on the curseforge page you can find the ic2c discord server.

I wrote you in discord.

**Comment by Speiger** [comment]
@innerdev and you didn't answer my question.
Do you have a way to reproduce the crash in a consistent way?
Because I need to be able to "reproduce" it otherwise i can not really test it, since the enet is really complex.

**Comment by Speiger** [comment]
@innerdev next time look at the "roles" channel where it says:
"Please pick the channels you want to see, so you wont be spammed with everything".
But oh well...

**Comment by innerdev** [comment]
> @innerdev and you didn't answer my question. Do you have a way to reproduce the crash in a consistent way? Like a list of instructions of what to do. Because I need to be able to "reproduce" it otherwise i can not really test it, since the enet is really complex.

Didn't answer because was not sure. But now I am - yes, I can reproduce it in a sonsistent way. But not lika a list of instructions, because the bug not showing up in a new clean world, dont know why. As I said I have world dump and everything.

Wait a second, I'll try to send you few screenshots via discord again :/

**Comment by Speiger** [comment]
@innerdev thank you.
This actually helped.
Here is the actual problem:
If a EnergyStorage/Transformer is connected by 3 sides (1 being the output and 2 being the inputs) by the same wire and causing a loop.
If they do unload this can lead to a crash.

Simple temp fix:
If you need to connect input/output use a Transformer to make a 1 way direction for power to flow so the output doesn't touch the input.

Example images:
[Crashing](https://media.discordapp.net/attachments/896498202969272350/1067882003678101594/not_ok2.png)
[NonCrashing](https://cdn.discordapp.com/attachments/896498202969272350/1067881936065929237/its_ok.png)

**Comment by Speiger** [comment]
Hopefully fixed
