### ISSUE TITLE
Crash recycler

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#60]
java.lang.NullPointerException: Ticking block entity
	at ic2.api.recipe.RecipeInputItemStack.matches(RecipeInputItemStack.java:24)
	at ic2.core.block.machine.tileentity.TileEntityRecycler.getIsItemBlacklisted(TileEntityRecycler.java:213)
	at ic2.core.block.machine.tileentity.TileEntityRecycler$RecyclerRecipeManager.getOutputFor(TileEntityRecycler.java:281)
	at ic2.core.block.machine.tileentity.TileEntityRecycler.operate(TileEntityRecycler.java:74)
	at ic2.core.block.machine.tileentity.TileEntityElectricMachine.func_145845_h(TileEntityElectricMachine.java:148)
	at net.minecraft.world.World.func_72939_s(World.java:2511)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.api.recipe.RecipeInputItemStack.matches(RecipeInputItemStack.java:24)
	at ic2.core.block.machine.tileentity.TileEntityRecycler.getIsItemBlacklisted(TileEntityRecycler.java:213)
	at ic2.core.block.machine.tileentity.TileEntityRecycler$RecyclerRecipeManager.getOutputFor(TileEntityRecycler.java:281)
	at ic2.core.block.machine.tileentity.TileEntityRecycler.operate(TileEntityRecycler.java:74)
	at ic2.core.block.machine.tileentity.TileEntityElectricMachine.func_145845_h(TileEntityElectricMachine.java:148)

Hello Speiger. This crash occurred when connecting pipes of Thermal Dynamics to two recyclers. The pipes are connected to the chest in which lies Cobblestone. If the chest is empty and then put him in Cobblestone(Scaffold), Cobblestone gets the first recycler, and then the second. When Cobblestone falls in the second recycler, then comes the crash.

**Comment by Speiger** [comment]
Thanks will check that after the current work is done^^

**Comment by Speiger** [comment]
Yeah was a derp bug. Really easy fixed ^^" Thanks
