### ISSUE TITLE
Issue with the village-o-mat

### ISSUE THREAD

**Issue by DAONE33** [TinyModularThings/IC2Classic#743]
hi i am really loveing ic2 classic amazing mod  but i mess about in creative while learning the mod i was messing about with the village o-mat and their was a lot of villages in the area and when interating with it for the second time it crash minecraft to desktop
I am not a coder or programmer so aplogies if it not directly casue by this block/item village-o-mat

java.lang.NullPointerException: Cannot invoke "ic2.core.block.machines.logic.villager.VillagerTradeList.findIndex(ic2.core.block.machines.logic.villager.VillagerTrade)" because the return value of "ic2.core.block.machines.logic.villager.VillagerList.getTrade(java.util.UUID)" is null
	at ic2.core.block.machines.components.hv.villager.VillagerOMatComponent.trigger(VillagerOMatComponent.java:156) ~[IC2Classic-1.19.2-2.0.5.jar%23323!/:1.19.2-2.0.5] {re:classloading}
	at ic2.core.block.machines.components.hv.villager.VillagerOMatComponent.lambda$init$0(VillagerOMatComponent.java:128) ~[IC2Classic-1.19.2-2.0.5.jar%23323!/:1.19.2-2.0.5] {re:classloading}
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23399!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

crash log
[crash-2023-04-09_19.23.58-client.txt](https://github.com/TinyModularThings/IC2Classic/files/11186117/crash-2023-04-09_19.23.58-client.txt)

thanks in advance hope this helps 
[crash-2023-04-10_11.24.26-client.txt](https://github.com/TinyModularThings/IC2Classic/files/11189958/crash-2023-04-10_11.24.26-client.txt)

**Comment by Speiger** [comment]
Please don't close/open the issue to get more attention.
All that will result in, is that you receive a ban.

I will address this issue next time i work on a patch.

**Comment by DAONE33** [comment]
can t reproduce

**Comment by DAONE33** [comment]
aplogies never used github before
