### ISSUE TITLE
Missing rubber wood leave texture

### ISSUE THREAD

**Issue by DewDrop-99** [TinyModularThings/IC2Classic#765]
Hello,

The texture from rubber wood leaves is missing and isn't working with the mod "Falling Leaves" and "Every Compact"

![2023-05-16_01 23 58](https://github.com/TinyModularThings/IC2Classic/assets/49823183/5be6814c-f81b-4165-bb8c-2427f6592f17)

**Comment by Speiger** [comment]
@DewDrop-99 please provide logs? That would help.

**Comment by DewDrop-99** [comment]
@Speiger 

This is the part related with Falling Leaves:

```
[00:42:58] [Render thread/ERROR]: Fail to generate Leaf Particle texture for type ic2:rubber : java.io.FileNotFoundException: Could not find any texture associated to the given block ic2:rubber_leaves
[00:42:58] [Render thread/ERROR]: Could not generate heavy leaf pile texture for type ic2:rubber
java.io.FileNotFoundException: Could not find any texture associated to the given block ic2:rubber_leaves
	at net.mehvahdjukaar.moonlight.api.resources.RPUtils.findFirstBlockTextureLocation(RPUtils.java:100) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.RPUtils.findFirstBlockTextureLocation(RPUtils.java:58) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$6(ClientDynamicResourcesHandler.java:232) ~[immersive_weathering-1.19.2-1.2.9-forge.jar%23861!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:227) ~[immersive_weathering-1.19.2-1.2.9-forge.jar%23861!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:111) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:81) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.lambda$postEvent$5(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.2.32-forge.jar%23936!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.handler$flh000$dynamicPackEarlyReload(MultiPackResourceManager.java:1534) ~[client-1.19.2-20220805.130853-srg.jar%231117!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:61) ~[client-1.19.2-20220805.130853-srg.jar%231117!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:44) ~[client-1.19.2-20220805.130853-srg.jar%231117!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%231117!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%231117!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231117!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

```
[latest.log](https://github.com/TinyModularThings/IC2Classic/files/11485520/latest.log)

I'm sending the full log too.

**Comment by Speiger** [comment]
@DewDrop-99 please report this bug to Moonlight/ImmersiveWeathering with the following information:
```
IC2C doesn't use JsonModels. It has its own Model Loader.
The IBakedModel API from minecraft is fully supported and every blockstate gives back a proper particle texture that is needed.
In general the IBakedModel solution is faster then deserializing every Model twice.
While both ways are legit, i ask kindly that you please add a fallback method that scan the IBakedModel if no JsonFile is found/no texture is found in the JsonFile.

IC2C classifies that as Moonlight/Immersive Weathering Bug
```
