### ISSUE TITLE
Rubberwood sign placement crashes game of any client in radius of it

### ISSUE THREAD

**Issue by Jessimo223** [TinyModularThings/IC2Classic#788]
On a multiplayer server, a friend has placed a rubberwood sign and it's making it impossible to enter an area of our map without immediately crashing the game with a white screen.

<details>
<summary>Crashlog</summary>
<p>

The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$12" is null

latest.log output (from crash):

[31May2023 07:14:32.705] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[31May2023 07:14:32.705] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[31May2023 07:14:32.705] [Render thread/INFO] [mezz.jei.library.startup.JeiStarter/]: Stopping JEI
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:minecraft ...
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:minecraft took 14.90 ?s
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: quarryplus:jei_recipe ...
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: quarryplus:jei_recipe took 2.000 ?s
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:gui ...
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:gui took 1.100 ?s
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:debug ...
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:debug took 1.500 ?s
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:forge_gui ...
[31May2023 07:14:32.706] [Render thread/INFO] [mezz.jei.forge.plugins.forge.ForgeGuiPlugin/]: Stopping JEI GUI
[31May2023 07:14:32.709] [JEI GUI Config file watcher/INFO] [mezz.jei.core.config.file.FileWatcherThread/]: FileWatcher was interrupted, stopping.
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:forge_gui took 2.982 ms
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: siegemachines:jei_plugin ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: siegemachines:jei_plugin took 3.500 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: decorative_blocks:main ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: decorative_blocks:main took 1.800 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: botanypots:jei_support ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: botanypots:jei_support took 1.300 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: clayworks:clayworks ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: clayworks:clayworks took 1.300 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: supplementaries:jei_plugin ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: supplementaries:jei_plugin took 1.500 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: immersiveengineering:main ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: immersiveengineering:main took 1.100 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: simplylight:jei_plugin ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: simplylight:jei_plugin took 1.100 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: waila:jei ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: waila:jei took 1.000 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: car:car ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: car:car took 1.000 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: curios:curios ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: curios:curios took 1.100 ?s
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: create:jei_plugin ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: create:jei_plugin took 900.0 ns
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: patchouli:patchouli ...
[31May2023 07:14:32.709] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: patchouli:patchouli took 900.0 ns
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: ic2:core ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: ic2:core took 2.300 ?s
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: camera:camera ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: camera:camera took 1.300 ?s
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: simplehats:jei_compat ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: simplehats:jei_compat took 900.0 ns
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: bigreactors:jeiplugin ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: bigreactors:jeiplugin took 1.200 ?s
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: fantasyfurniture:jei_integration ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: fantasyfurniture:jei_integration took 1.100 ?s
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: createaddition:jei_plugin ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: createaddition:jei_plugin took 1.000 ?s
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:internal ...
[31May2023 07:14:32.710] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable: jei:internal took 1.000 ?s
[31May2023 07:14:32.710] [JEI Library Config file watcher/INFO] [mezz.jei.core.config.file.FileWatcherThread/]: FileWatcher was interrupted, stopping.
[31May2023 07:14:32.773] [Render thread/INFO] [journeymap/]: Mapping halted in W:\RelishCraft 2 Mod Harder\journeymap\data\mp\Relishcraft~2_64357694~2d13~431b~8fdf~cab660b77675\minecraft:overworld
[31May2023 07:14:38.661] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[31May2023 07:14:38.965] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:111) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:280) ~[rubidium-0.6.2a.jar%23300!/:?]
	at net.minecraft.client.renderer.LevelRenderer.handler$zbc000$onRenderTileEntities(LevelRenderer.java:5272) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1267) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$12" is null
	at net.minecraft.client.renderer.blockentity.SignRenderer.m_6922_(SignRenderer.java:86) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.blockentity.SignRenderer.m_6922_(SignRenderer.java:41) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:104) ~[client-1.19.2-20220805.130853-srg.jar%23317!/:?]
	... 23 more
[31May2023 07:14:38.970] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 9917b4a7-cd2e-4ae9-a07a-adf8231cc0c3
[31May2023 07:14:38.975] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ed6b14cb-043c-41ab-ace6-ceb38c91141d

</p>
</details>

**Comment by Jessimo223** [comment]
Update - this happens on any IC2Classic sign placed down.

**Comment by Speiger** [comment]
@Jessimo223 please make sure this happens with ONLY IC2C installed as #606 showed this is not a ic2c Bug.

**Comment by Speiger** [comment]
Closing because no further reports and no proof that this is a IC2 Only Issue.
