### ISSUE TITLE
Datapack export creates empty zip

### ISSUE THREAD

**Issue by enigmaquip** [TinyModularThings/IC2Classic#842]
running `/ic2c_export` in a single player world with cheats enabled just creates an empty zip file at `<instance>/config/ic2/Datapack.zip`

**Comment by Speiger** [comment]
please provide a game log where you attempted to use the datapack export.

**Comment by enigmaquip** [comment]
```

[07/17/2023 00:10:29 AM] java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because the return value of "ic2.core.utils.collection.FunctionRegistry$BiFunctionRegistry.getKey(Object)" is null
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/ic2@1.19.2-2.0.6.2/ic2.core.platform.recipes.misc.IngredientRegistry.serializeModifier(IngredientRegistry.java:157)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/ic2@1.19.2-2.0.6.2/ic2.core.platform.recipes.crafting.ShapedIC2Recipe.serialize(ShapedIC2Recipe.java:101)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/ic2@1.19.2-2.0.6.2/ic2.core.platform.recipes.misc.GlobalRecipes.serialize(GlobalRecipes.java:191)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/ic2@1.19.2-2.0.6.2/ic2.core.platform.recipes.misc.GlobalRecipes.createRecipeFiles(GlobalRecipes.java:180)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/ic2@1.19.2-2.0.6.2/ic2.core.platform.events.ExportCommand.execute(ExportCommand.java:45)
[07/17/2023 00:10:29 AM] 	at MC-BOOTSTRAP/brigadier@1.0.18/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.commands.Commands.m_242674_(Commands.java:240)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerGamePacketListenerImpl.java:1239)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:1217)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
[07/17/2023 00:10:29 AM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
[07/17/2023 00:10:29 AM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
[07/17/2023 00:10:29 AM] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Speiger** [comment]
Please drag & drop the entire game log into the github issue.
Because there is 0 information if this is a IC2Classic only issue or a "modpack issue"

**Comment by enigmaquip** [comment]
https://mclo.gs/3Ttj9J9

**Comment by enigmaquip** [comment]
Does seem to be a conflict in my pack, sorry I should've tested that first. Is working in a clean install

**Comment by Speiger** [comment]
@enigmaquip since the datapack is just there to simplify the ic2c recipe changing (you should never include the entire pack and just keep what you want to change) i consider this as a non issue. 
But yeah it seems this is a modpack issue. Note that the zip created isn't a finalized datapack, it is like a 99% done pack so people still have to do things.

Also glad that we were able to solve the problem

**Comment by GitJhopa** [comment]
I put my addon for IC2 and registered /ic2export and in fact received an empty datapack.

**Comment by Speiger** [comment]
@GitJhopa that is a bug with your Addon. Not a IC2Classic issue.
