### ISSUE TITLE
Upgrade Crash

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#87]
I tried putting a redstone inverter upgrade in the induction furnace and the game crashed:

---- Minecraft Crash Report ----
// There are four lights!

Time: 18/07/15 11:42
Description: Updating screen events

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at ic2.core.block.machine.tileentity.TileEntityAdvancedMachine.getSupportedTypes(TileEntityAdvancedMachine.java:591)
	at ic2.core.slot.SlotUpgrade.func_75214_a(SlotUpgrade.java:28)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146273_a(GuiContainer.java:462)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:311)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.block.machine.tileentity.TileEntityAdvancedMachine.getSupportedTypes(TileEntityAdvancedMachine.java:591)
	at ic2.core.slot.SlotUpgrade.func_75214_a(SlotUpgrade.java:28)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146273_a(GuiContainer.java:462)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:311)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

**Comment by Speiger** [comment]
Hating scala so much....
I used a function Arrays.asList which scala and java provide (i want the java one) and it used the scala one... (Simply that i can insert the types better into a list i made that one)

**Comment by Speiger** [comment]
Fixed
