### ISSUE TITLE
Server Crash 1.19.2

### ISSUE THREAD

**Issue by IchigoGames** [TinyModularThings/IC2Classic#875]
Multiplayer crash.

Minecraft 1.19.2
Forge version 43.2.23
IC2Classic-1.19.2-2.0.7.1
Pack my pack Tekkit The Resurrection

Info 
Pretty sure its player build but i'm not sure if its the player joining at there base or loading into some ones base near them and
im not sure what it is that's crashing other than it being from this mod here's the crash report i can also send logs if you want.

[crash-2023-09-29_17.01.03-server.txt](https://github.com/TinyModularThings/IC2Classic/files/12774235/crash-2023-09-29_17.01.03-server.txt)

**Comment by Speiger** [comment]
@IchigoGames there is a config that is "deprecated" but still working that basically catches the crash.
Its only preventing the Symptom not fixing the actual issue.

I thought that i fixed this with 2.0.7.0 because i found the underlying issue (at least i thought that)

Would you be so kind and provide a reproduce-able setup?

**Comment by IchigoGames** [comment]
i will when i find it looking for the player now if i find them i can go check out there base unless its a crash that happens as soon as the base loads in not sure how to do a reproduce-able setup if thats the case.

**Comment by gudvinr** [comment]
I think I have the same issue:

<details><summary>crash log</summary>

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2023-11-04 03:05:27
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
	at ic2.core.energy.EnergyNetLocal.getConnectivity(EnergyNetLocal.java:859) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading}
	at ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:877) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading}
	at ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:223) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading}
	at ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading}
	at ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:137) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading}
	at ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading}
	at ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:449) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading,pl:runtimedistcleaner:A}
	at ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic) ~[IC2Classic-1.19.2-2.0.7.1.jar%23111!/:1.19.2-2.0.7.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:829) ~[forge-1.19.2-43.3.2-universal.jar%23124!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```
</details>

I can probably send you copy of the world with rough location of the chunk where issue occurs if you share an email. World size is around 800MB.

**Comment by Speiger** [comment]
@gudvinr how big is the modpack?

**Comment by gudvinr** [comment]
> how big is the modpack?

```
Mod List: 
	server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: NOSIGNATURE
	radon-0.8.2.jar                                   |Radon                         |radon                         |0.8.2               |DONE      |Manifest: NOSIGNATURE
	radium-0.8.2.jar                                  |Radium                        |radium                        |0.8.2               |DONE      |Manifest: NOSIGNATURE
	theoneprobe-1.19-6.2.2.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.2          |DONE      |Manifest: NOSIGNATURE
	DungeonCrawl-1.19-2.3.12.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.12              |DONE      |Manifest: NOSIGNATURE
	Chunk+Pregenerator-1.19-4.3.0.jar                 |Chunk Pregenerator            |chunkpregen                   |1.19-4.3.0          |DONE      |Manifest: NOSIGNATURE
	forge-1.19.2-43.3.2-universal.jar                 |Forge                         |forge                         |43.3.2              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Incendium_1.19.3_v5.1.6.jar                       |Incendium                     |incendium                     |5.1.6               |DONE      |Manifest: NOSIGNATURE
	curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |DONE      |Manifest: NOSIGNATURE
	IC2Classic-1.19.2-2.0.7.1.jar                     |IC2 Classic                   |ic2                           |1.19.2-2.0.7.1      |DONE      |Manifest: NOSIGNATURE
	journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |DONE      |Manifest: NOSIGNATURE
	jei-1.19.2-forge-11.6.0.1018.jar                  |Just Enough Items             |jei                           |11.6.0.1018         |DONE      |Manifest: NOSIGNATURE
```

**Comment by Speiger** [comment]
@gudvinr that is actually the perfect modpack.
Barely any mods that are required to stay outside of ic2c. (Like 1 or 2)

Yeah please send me the world. Maybe a Multimc export?
Then maybe i can finally fix this issue :)

**Comment by gudvinr** [comment]
Sent you an email (to your git email address) with google drive link to world archive.

**Comment by Speiger** [comment]
@gudvinr yeah i have noticed **still recovering from the small heart attack**
(jokes aside, thank you)

**Comment by gudvinr** [comment]
Had another crash like that. I am not sure if it's the same issue because in other 2 instances it was just people minding their own business without actively interacting with IC2C entities.

Now server crashed while I was removing cabling with chainsaw (error is the same):
There was another row of golden cables above which I was removing when crash occurred.

![assembly](https://github.com/TinyModularThings/IC2Classic/assets/1712806/9ed51d78-0cec-4b0f-a668-ada54111eed1)
