### ISSUE TITLE
Crops for some reason get a index out of bound exception...

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#908]
![image](https://cdn.discordapp.com/attachments/896498202969272350/1172211733532786751/image.png?ex=655f7e3f&is=654d093f&hm=24119a2db87885b616b2ff9db8f1c54970caa029c797dfb2b0033e9204dca4d7&)

Exception:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(Unknown Source) ~[?:?]
	at java.util.ArrayList.add(Unknown Source) ~[?:?]
	at ic2.probeplugin.info.CropComponent.addInfo(CropComponent.java:122) ~[IC2Classic-1.19.2-2.0.7.1.jar%23524!/:1.19.2-2.0.7.1]
	at ic2.probeplugin.info.CropComponent.addInfo(CropComponent.java:38) ~[IC2Classic-1.19.2-2.0.7.1.jar%23524!/:1.19.2-2.0.7.1]
	at ic2.probeplugin.info.ITileInfoComponent.addTileInfo(ITileInfoComponent.java:33) ~[IC2Classic-1.19.2-2.0.7.1.jar%23524!/:1.19.2-2.0.7.1]
	at ic2.probeplugin.base.ProbeTileListener.addProbeInfo(ProbeTileListener.java:59) ~[IC2Classic-1.19.2-2.0.7.1.jar%23524!/:1.19.2-2.0.7.1]
	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:137) ~[theoneprobe-1.19-6.2.2.jar%23634!/:1.19-6.2.2]
	at mcjty.theoneprobe.network.PacketGetInfo.lambda$handle$0(PacketGetInfo.java:100) ~[theoneprobe-1.19-6.2.2.jar%23634!/:1.19-6.2.2]
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Speiger** [comment]
Fixed this, but this is more of a bandage fix then addressing the real issue.
but i need more info then that sadly to address the underlying issue.
