### ISSUE TITLE
Crash when placing down copper cable on a batbox

### ISSUE THREAD

**Issue by Micaxs** [TinyModularThings/IC2Classic#914]
**Crash report:**
`Time: 2023-11-19 21:54:55
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
	at ic2.core.energy.EnergyNetLocal.getConnectivity(EnergyNetLocal.java:861) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:879) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:242) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:137) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:449) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading,pl:runtimedistcleaner:A}
	at ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:829) ~[forge-1.19.2-43.3.5-universal.jar%23586!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}`

**Setup:**
3 batbox connected to a lv compact solar panel -> 2 batbox connected to a electric furnace and conencting the 3rd bvatbox to the cables going to furnace = crash.

Hope that's enough information to debug the issue and potentionally fix the issue.

Occurred on FTB Genesis 1.2.0 modpack if that's relevant.

**Comment by Trinsdar** [comment]
was already fixed, there's a new version of ic2 classic out

**Comment by Speiger** [comment]
@Micaxs FTB Genesis is having a broken version it is fixed in the latest version.
Update FTB genesis :)
