### ISSUE TITLE
[FTB Genesis] NullPointerException on Ticking block entity CropTileEntity, crops.ICrop.getCropType()

### ISSUE THREAD

**Issue by Ererfel** [TinyModularThings/IC2Classic#931]
Server crashes regularly with error the included stacktrace
Playing FTB Genesis, advanced to the second tier farming simulation ( can provide the map for further testing ) 
Appeared when starting to crossbreed netherwarth in low light environment
It doesn't seem to come from any specific tiles in space
Currently trying to remove all crossbreed of the netherwarth to check the hypothesis
```
-- Head --
Thread: Server thread
Suspected Mod: 
	IC2 Classic (ic2), Version: 1.19.2-2.0.8.1
		Issue tracker URL: https://github.com/TinyModularThings/IC2Classic/issues
		at TRANSFORMER/ic2@1.19.2-2.0.8.1/ic2.core.block.crops.CropTileEntity.update(CropTileEntity.java:677)
Stacktrace:
	at ic2.core.block.crops.CropTileEntity.update(CropTileEntity.java:677) ~[IC2Classic-1.19.2-2.0.8.1.jar%23522!/:1.19.2-2.0.8.1] {re:mixin,re:classloading,pl:mixin:APP:noweed.mixins.json:CropTrampleMixin,pl:mixin:APP:noweed.mixins.json:WeedGrowMixin,pl:mixin:A}
	at ic2.core.block.crops.CropTileEntity.onTick(CropTileEntity.java:633) ~[IC2Classic-1.19.2-2.0.8.1.jar%23522!/:1.19.2-2.0.8.1] {re:mixin,re:classloading,pl:mixin:APP:noweed.mixins.json:CropTrampleMixin,pl:mixin:APP:noweed.mixins.json:WeedGrowMixin,pl:mixin:A}
	at ic2.core.block.base.features.ITickListener.tick(ITickListener.java:44) ~[IC2Classic-1.19.2-2.0.8.1.jar%23522!/:1.19.2-2.0.8.1] {re:classloading,re:mixin}
	at ic2.core.block.base.features.ITickListener.update(ITickListener.java:55) ~[IC2Classic-1.19.2-2.0.8.1.jar%23522!/:1.19.2-2.0.8.1] {re:classloading,re:mixin}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:ic2.mixins.json:server.LevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:LevelAccess,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: ic2:crop_sticks // ic2.core.block.crops.CropTileEntity
	Block: Block{ic2:crop_sticks}[light=0,waterlogged=false]
	Block location: World: (-14,49,107), Section: (at 2,1,11 in -1,3,6; chunk contains blocks -16,0,96 to -1,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{ic2:crop_sticks}[light=0,waterlogged=false]
	Block location: World: (-14,49,107), Section: (at 2,1,11 in -1,3,6; chunk contains blocks -16,0,96 to -1,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:ic2.mixins.json:server.LevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:LevelAccess,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
```
[crash-2023-12-12_10.34.31-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13646336/crash-2023-12-12_10.34.31-server.txt)
[crash-2023-12-12_10.19.50-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13646348/crash-2023-12-12_10.19.50-server.txt)

**Comment by Speiger** [comment]
duplicate #922 
will be fixed in the next patch. 
Just swamped.

To avoid: Terrward/netherward dies during its crop boost tick.
That is the reason the game crashed.
